# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'generate_clients') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    Puppet::Parser::Functions.autoloader.loadall

    # This searches top scope for variables in the style
    # $bacula_client_mynode with values in format
    # fileset=Basic:noHome,client_schedule=Hourly
    self.to_hash.each do |variable,value|
      if variable =~ /^bareos_client_.*$/
        client = variable[14..-1]

        begin
          parameters = Hash[ value.split(',').map do |val|
            val_array = val.split('=',2)
            if val_array.size != 2
              raise Puppet::ParseError, 'Could not parse parameters given. Please check your format'
            end
            if [nil,''].include? val_array[0] or [nil,''].include? val_array[1]
              raise Puppet::ParseError, 'Could not parse parameters given. Please check your format'
            end
            val_array
          end ]
        rescue
          raise Puppet::ParseError, 'Could not parse parameters given. Please check your format'
        end

        function_create_resources('bareos::client::config', {client => parameters})
      end
    end

    begin
      function_create_resources('bareos::client::config', args[0])
    rescue => e
      raise Puppet::ParseError, e
    end
  
  end
end
